### ISSUE TITLE
onReport - how to pass metrics to a callback function

### ISSUE THREAD

**Issue by cluebattery** [clappr/clappr-stats#13]
Perhaps I'm dense or need more caffeine - but alas, I have yet to be able to understand how to override the default console.log(metrics) that gets called with onReport.

I honestly have never seen this form of syntax prior today:

`onReport: (metrics) => { console.log(metrics) }`

So perhaps I'm not well enough versed, but can I get some guidance on how I can pass the metrics that are being sent to console log to an external function?

I have tried:

`clapperStats: {
        runEach: 5000,
        onReport: function(metrics) { myFunction(metrics); }
    },
`

`
clapperStats: {
        runEach: 5000,
        onReport: (metrics) => { myFunction(metrics) }
    },
`

with something like this outside the player, 

`
function myFunction(metrics = null) {
   console.log('You rang?');
   console.log(metrics);
}
`

And nothing I have tried has worked. I see the default console.logs happening like clockwork, but "myFunction" is never touched. 

Barring forking the code and replacing the default, you have successfully triggered my impostor syndrome and I beg for a light in this darkness.

All that said, great work here - I'm just a bit confused on this one aspect.

**Comment by leandromoreira** [comment]
I think it might be a typo where you see `clapperStats` change it to `clapprStats`

**Comment by cluebattery** [comment]
This is why you shouldn't work on stuff at 2AM... Thanks.

**Comment by cluebattery** [comment]
Quick question:

```
clapprStats: {
   runEach: 5000,
   onReport: (metrics) => { myFunction(metrics) }
},
```

Does work - but it makes my IDE (PHPStorm) Barf - is there an alternate format make this call that won't cause that issue. As I mentioned, that is a syntax I have never seen - and apparently my IDE hasn't either.

**Comment by leandromoreira** [comment]
@cluebattery it's ECMAScript6 (kinda the new Javascript specification), you should be able to use any kind of JS:

```javascript
function myFunction(metrics){
      console.log(metrics);
}

clapprStats: {
   runEach: 5000,
   onReport: myFunction
},
```

**Comment by cluebattery** [comment]
Thanks again.
